DROP TABLE EDW.PROCESS_AUDIT CASCADE CONSTRAINTS;

CREATE TABLE EDW.PROCESS_AUDIT
(
  BATCH_ID         NUMBER                       NOT NULL,
  AUDIT_TYPE       VARCHAR2(50 BYTE)            NOT NULL,
  LOAD_TYPE_PARM   VARCHAR2(2 BYTE)             NOT NULL,
  START_DATE_PARM  DATE                         NOT NULL,
  END_DATE_PARM    DATE                         NOT NULL,
  SOURCE_COUNT     NUMBER                       NOT NULL,
  TARGET_COUNT     NUMBER                       NOT NULL,
  INSERT_COUNT     NUMBER,
  UPDATE_COUNT     NUMBER,
  DELETE_COUNT     NUMBER,
  AUDIT_OK         NUMBER(1)                    NOT NULL,
  COMMENTS         VARCHAR2(2000 BYTE),
  REC_INSERT_DATE  DATE                         DEFAULT sysdate
)
TABLESPACE EDW_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--
--GRANT SELECT ON EDW.PROCESS_AUDIT TO DM_INT_RO;
--
--GRANT DELETE, INSERT, SELECT, UPDATE ON EDW.PROCESS_AUDIT TO DM_INT_RW;
